use std::collections::HashMap;

pub fn get_hashmap_cities_to_urls_hostel_world() -> HashMap<String, String> {
    let mut hashmap: HashMap<String, String> = HashMap::new();
    hashmap.insert("Berlin".to_string(), "berlin".to_string());
    hashmap.insert("Bitburg".to_string(), "bitburg".to_string());
    hashmap.insert("Dresden".to_string(), "dresden".to_string());
    hashmap.insert("Dusseldorf".to_string(), "dusseldorf".to_string());
    hashmap.insert("Munich".to_string(), "munich".to_string());
    hashmap.insert("Osnabrück".to_string(), "osnabrueck".to_string());
    hashmap.insert("Ingolstadt".to_string(), "ingolstadt".to_string());
    hashmap.insert("Frankfurt".to_string(), "frankfurt".to_string());
    hashmap.insert("Nuremberg".to_string(), "nuremberg".to_string());
    hashmap.insert("Bremen".to_string(), "bremen".to_string());
    hashmap.insert("Hamburg".to_string(), "hamburg".to_string());
    hashmap.insert("Hanover".to_string(), "hanover".to_string());
    hashmap.insert("Cologne".to_string(), "cologne".to_string());
    hashmap.insert("Heidelberg".to_string(), "heidelberg".to_string());
    hashmap.insert("Stuttgart".to_string(), "stuttgart".to_string());
    hashmap.insert("Bruchmuehlbach".to_string(), "bruchmuehlbach".to_string());
    hashmap.insert("Kiel".to_string(), "kiel".to_string());
    hashmap.insert("Rechberghausen".to_string(), "rechberghausen".to_string());
    hashmap.insert("Sieber".to_string(), "sieber".to_string());
    hashmap.insert("Friedrichshafen".to_string(), "friedrichshafen".to_string());
    hashmap.insert("Füssen".to_string(), "fuessen".to_string());
    hashmap.insert("Weimar".to_string(), "weimar".to_string());
    hashmap.insert("Rothenburg ob der Tauber".to_string(), "rothenburg-ob-der-tauber".to_string());
    hashmap.insert("Rantum-Sylt".to_string(), "rantum-sylt".to_string());
    hashmap.insert("Wuerzburg".to_string(), "wuerzburg".to_string());
    hashmap.insert("Wismar".to_string(), "wismar".to_string());
    hashmap.insert("Mannheim".to_string(), "mannheim".to_string());
    hashmap.insert("Bottrop".to_string(), "bottrop".to_string());
    hashmap.insert("Neuruppin".to_string(), "neuruppin".to_string());
    hashmap.insert("Halle".to_string(), "halle".to_string());
    hashmap.insert("Rostock".to_string(), "rostock".to_string());
    hashmap.insert("Regensburg".to_string(), "regensburg".to_string());
    hashmap.insert("Erfurt".to_string(), "erfurt".to_string());
    hashmap.insert("Chemnitz".to_string(), "chemnitz".to_string());
    hashmap.insert("Frankfurt Hahn".to_string(), "frankfurt-hahn".to_string());
    hashmap.insert("Leipzig".to_string(), "leipzig".to_string());
    hashmap.insert("Stralsund".to_string(), "stralsund".to_string());
    hashmap.insert("Freiburg".to_string(), "freiburg".to_string());
    hashmap.insert("Essen".to_string(), "essen".to_string());
    hashmap.insert("Solingen".to_string(), "solingen".to_string());
    hashmap.insert("Königs-Wusterhausen".to_string(), "konigs-wusterhausen".to_string());
    hashmap.insert("Kuhlungsborn".to_string(), "kuhlungsborn".to_string());
    hashmap.insert("Kassel".to_string(), "kassel".to_string());
    hashmap.insert("Isny Allgau".to_string(), "isny-allgau".to_string());
    hashmap.insert("Bonn".to_string(), "bonn".to_string());
    hashmap.insert("Naumburg".to_string(), "naumburg".to_string());
    hashmap.insert("Filderstadt".to_string(), "filderstadt".to_string());
    hashmap.insert("Dallgow".to_string(), "dallgow".to_string());
    hashmap.insert("Passau".to_string(), "passau".to_string());
    hashmap.insert("Baden-Baden".to_string(), "baden-baden".to_string());
    hashmap.insert("Kastellaun".to_string(), "kastellaun".to_string());
    hashmap.insert("Bad Liebenstein".to_string(), "bad-liebenstein".to_string());
    hashmap.insert("Unteruhldingen".to_string(), "unteruhldingen".to_string());
    hashmap.insert("Bayerisch Gmain ".to_string(), "bayerisch-gmain".to_string());
    hashmap.insert("Ahaus".to_string(), "ahaus".to_string());
    hashmap.insert("Goettingen".to_string(), "goettingen".to_string());
    hashmap.insert("Weiden ".to_string(), "weiden".to_string());
    hashmap.insert("Wieden ".to_string(), "wieden".to_string());
    hashmap.insert("Jena".to_string(), "jena".to_string());
    hashmap.insert("Oranienburg ".to_string(), "oranienburg".to_string());
    hashmap.insert("Lübeck".to_string(), "luebeck".to_string());
    hashmap.insert("Hohenlinden ".to_string(), "hohenlinden".to_string());
    hashmap.insert("Darmstadt".to_string(), "darmstadt".to_string());
    hashmap.insert("Wernigerode".to_string(), "wernigerode".to_string());
    hashmap.insert("Potsdam".to_string(), "potsdam".to_string());
    hashmap.insert("Floersheim am Main ".to_string(), "floersheim-am-main".to_string());
    hashmap.insert("Aachen".to_string(), "aachen".to_string());
    hashmap.insert("Augsburg ".to_string(), "augsburg".to_string());
    hashmap.insert("Magdeburg".to_string(), "magdeburg".to_string());
    hashmap.insert("Koblenz Kamp-Bornhofen".to_string(), "koblenz-kamp-bornhofen".to_string());
    hashmap.insert("Vohenstrauss".to_string(), "vohenstrauss".to_string());
    hashmap.insert("Koblenz".to_string(), "koblenz".to_string());
    hashmap.insert("Schmölln".to_string(), "schmoelln".to_string());
    hashmap.insert("Garmisch-Partenkirchen".to_string(), "garmisch-partenkirchen".to_string());
    hashmap.insert("Kamp-Bornhofen".to_string(), "kamp-bornhofen".to_string());
    hashmap.insert("Bremerhaven".to_string(), "bremerhaven".to_string());
    hashmap.insert("Offenbach am Main".to_string(), "offenbach-am-main".to_string());
    hashmap.insert("Hanau".to_string(), "hanau".to_string());
    hashmap.insert("Boppard".to_string(), "boppard".to_string());
    hashmap.insert("Schönberg".to_string(), "schoenberg".to_string());
    hashmap.insert("Riesa".to_string(), "riesa".to_string());
    hashmap.insert("Neuental".to_string(), "neuental".to_string());
    hashmap.insert("Dortmund".to_string(), "dortmund".to_string());
    hashmap.insert("Duisburg".to_string(), "duisburg".to_string());
    hashmap.insert("Staufen".to_string(), "staufen".to_string());
    hashmap.insert("Merseburg".to_string(), "merseburg".to_string());
    hashmap.insert("Sangerhausen".to_string(), "sangerhausen".to_string());
    hashmap.insert("Balticsea Lensahn".to_string(), "balticsea-lensahn".to_string());
    hashmap.insert("Flensburg".to_string(), "flensburg".to_string());
    hashmap.insert("Bochum".to_string(), "bochum".to_string());
    hashmap.insert("Oberammergau ".to_string(), "oberammergau".to_string());
    hashmap.insert("Dachau".to_string(), "dachau".to_string());
    hashmap.insert("Hattingen".to_string(), "hattingen".to_string());
    hashmap.insert("Bad Muskau".to_string(), "bad-muskau".to_string());
    hashmap.insert("Lindau".to_string(), "lindau".to_string());
    hashmap.insert("Lam".to_string(), "lam".to_string());
    hashmap.insert("Radevormwald".to_string(), "radevormwald".to_string());
    hashmap.insert("Winnenden".to_string(), "winnenden".to_string());
    hashmap.insert("Starnberg".to_string(), "starnberg".to_string());
    hashmap.insert("Bischofswiesen".to_string(), "bischofswiesen".to_string());
    hashmap.insert("Pulsnitz".to_string(), "pulsnitz".to_string());
    hashmap.insert("Esens".to_string(), "esens".to_string());
    hashmap.insert("Bad Reichenhall".to_string(), "bad-reichenhall".to_string());
    hashmap.insert("Schliersee".to_string(), "schliersee".to_string());
    hashmap.insert("Titisee-Neustadt".to_string(), "titisee-neustadt".to_string());
    hashmap.insert("Großalmerode".to_string(), "grossalmerode".to_string());
    hashmap.insert("Gummersbach".to_string(), "gummersbach".to_string());
    hashmap.insert("Thale".to_string(), "thale".to_string());
    hashmap.insert("Spiekeroog".to_string(), "spiekeroog".to_string());
    hashmap.insert("Bad Endorf".to_string(), "bad-endorf".to_string());
    hashmap.insert("Wittenberg".to_string(), "wittenberg".to_string());
    hashmap.insert("Winterberg".to_string(), "winterberg".to_string());
    hashmap.insert("Greifswald".to_string(), "greifswald".to_string());
    hashmap.insert("Middelhagen".to_string(), "middelhagen".to_string());
    hashmap.insert("Görlitz".to_string(), "goerlitz".to_string());
    hashmap.insert("Bad Wiessee".to_string(), "bad-wiessee".to_string());
    hashmap.insert("Bielefeld".to_string(), "bielefeld".to_string());
    hashmap.insert("Wiesbaden".to_string(), "wiesbaden".to_string());
    hashmap.insert("Sankt Peter-Ording".to_string(), "sankt-peter-ording".to_string());
    hashmap.insert("Schwaebisch Hall ".to_string(), "schwaebisch-hall".to_string());
    hashmap.insert("Hauenstein".to_string(), "hauenstein".to_string());
    hashmap.insert("Dinslaken".to_string(), "dinslaken".to_string());
    hashmap.insert("Burghausen".to_string(), "burghausen".to_string());
    hashmap.insert("Bayreuth".to_string(), "bayreuth".to_string());
    hashmap.insert("Karlsruhe".to_string(), "karlsruhe".to_string());
    hashmap.insert("Zingst".to_string(), "zingst".to_string());
    hashmap.insert("Volkach".to_string(), "volkach".to_string());
    hashmap.insert("Moers".to_string(), "moers".to_string());
    hashmap.insert("Lemgo".to_string(), "lemgo".to_string());
    hashmap.insert("Mettlach".to_string(), "mettlach".to_string());
    hashmap.insert("Bergisch Gladbach".to_string(), "bergisch-gladbach".to_string());
    hashmap.insert("Hagen".to_string(), "hagen".to_string());
    hashmap.insert("Schneizlreuth".to_string(), "schneizlreuth".to_string());
    hashmap.insert("Buching/Halblech".to_string(), "buching-halblech".to_string());
    hashmap.insert("Minden".to_string(), "minden".to_string());
    hashmap.insert("Goslar".to_string(), "goslar".to_string());
    hashmap.insert("Celle".to_string(), "celle".to_string());
    hashmap.insert("Eckernförde".to_string(), "eckernfoerde".to_string());
    hashmap.insert("Mühlhausen".to_string(), "muehlhausen".to_string());
    hashmap.insert("Germering".to_string(), "germering".to_string());
    hashmap.insert("Schwedeneck".to_string(), "schwedeneck".to_string());
    hashmap.insert("Wuppertal".to_string(), "wuppertal".to_string());
    hashmap.insert("Bacharach".to_string(), "bacharach".to_string());
    hashmap.insert("Dahme".to_string(), "dahme".to_string());
    hashmap.insert("Leibsch".to_string(), "leibsch".to_string());
    hashmap.insert("Wesendorf".to_string(), "wesendorf".to_string());
    hashmap.insert("Cuxhaven".to_string(), "cuxhaven".to_string());
    hashmap.insert("Hallbergmoos".to_string(), "hallbergmoos".to_string());
    hashmap.insert("Dietingen".to_string(), "dietingen".to_string());
    hashmap.insert("Kochel".to_string(), "kochel".to_string());
    hashmap.insert("Güstrow".to_string(), "guestrow".to_string());
    hashmap.insert("Guben".to_string(), "guben".to_string());
    hashmap.insert("Münster".to_string(), "munster".to_string());
    hashmap.insert("Hamelin".to_string(), "hamelin".to_string());
    hashmap.insert("Kreuzau".to_string(), "kreuzau".to_string());
    hashmap.insert("Haan".to_string(), "haan".to_string());
    hashmap
}